// Connections
export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_CONNECTION_LOADING = 'SET_CONNECTION_LOADING';
export const SET_CONNECTIONS = 'SET_CONNECTIONS';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';
export const DELETE_CONNECTION = 'DELETE_CONNECTION';
export const SHOW_CONNECTION_FORM = 'SHOW_CONNECTION_FORM';
export const HIDE_CONNECTION_FORM = 'HIDE_CONNECTION_FORM';

// Databases
export const SET_DB_LIST = 'SET_DB_LIST';
export const SET_DB_TO_EDIT = 'SET_DB_TO_EDIT';
export const TOGGLE_DATABASE_FORM = 'TOGGLE_DATABASE_FORM';
export const TOGGLE_DELETE_DATABASE_FORM = 'TOGGLE_DELETE_DATABASE_FORM';
export const TOGGLE_TABLE_VISIBILITY = 'TOGGLE_TABLE_VISIBILITY';
export const ADD_TO_DB_LIST = 'ADD_TO_DB_LIST';
export const DELETE_DATABASE = 'DELETE_DATABASE';
export const SET_DATABASE_FORM_ERROR = 'SET_DATABASE_FORM_ERROR';
export const SET_DELETE_DATABASE_CONFIRM_ERROR = 'SET_DELETE_DATABASE_CONFIRM_ERROR';

// Tables
export const SET_DB_TABLES = 'SET_DB_TABLES';
export const ADD_TO_TABLE_LIST = 'ADD_TO_TABLE_LIST';
export const DELETE_TABLE = 'DELETE_TABLE';
export const SET_TABLE_SIZE = 'SET_TABLE_SIZE';
export const SET_LAST_DB_RESULT = 'SET_LAST_DB_RESULT';
export const SET_TABLE_FORM_ERROR = 'SET_TABLE_FORM_ERROR';
export const TOGGLE_DELETE_TABLE_FORM = 'TOGGLE_DELETE_TABLE_FORM';
export const TOGGLE_TABLE_FORM = 'TOGGLE_TABLE_FORM';
export const SET_SELECTED_TABLE = 'SET_SELECTED_TABLE';
export const REMOVE_SELECTED_TABLE = 'REMOVE_SELECTED_TABLE';
export const UPDATE_SELECTED_TABLE = 'UPDATE_SELECTED_TABLE';
export const SET_DELETE_TABLE_CONFIRM_ERROR = 'SET_DELETE_TABLE_CONFIRM_ERROR';

// Query
export const SET_TABLE_QUERY = 'SET_TABLE_QUERY';
export const SET_TABLE_PAGE_LIMIT = 'SET_TABLE_PAGE_LIMIT';
export const SET_TABLE_SORT = 'SET_TABLE_SORT';
export const SET_FILTER_PREDICATE = 'SET_FILTER_PREDICATE';
export const SET_ORDER_BY_PREDICATE = 'SET_ORDER_BY_PREDICATE';

// View
export const TOGGLE_EXPLORER_BODY = 'TOGGLE_EXPLORER_BODY';
export const SET_ROW_EDIT = 'SET_ROW_EDIT';
export const SET_ROW_INLINE_EDIT = 'SET_ROW_INLINE_EDIT';
export const CANCEL_ROW_EDIT = 'CANCEL_ROW_EDIT';
export const SET_CODE_BODY_ERROR = 'SET_CODE_BODY_ERROR';
export const SET_CODE_BODY = 'SET_CODE_BODY';
